version: '3.8'

services:
  ekf-simulator:
    build: .
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: ["./run_simulation.sh", "--help"]
